#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { load } from "js-yaml";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT_DIR = join(ROOT, "content");
const OUTPUT_DIR = join(ROOT, "build", "cv");

const SITE_URL = "https://leonid.sh/";
const TELEGRAM_URL = "https://t.me/matyushinleonid";

const LABELS = {
  en: {
    education: "Education",
    experience: "Experience (Selected Projects)",
    projects: "Personal Projects",
    achievements: "Other Achievements",
    skills: "Technical Skills",
    email: "Email",
    telegram: "Telegram",
  },
  ru: {
    education: "Образование",
    experience: "Опыт работы",
    projects: "Персональные проекты",
    achievements: "Другие достижения",
    skills: "Технические навыки",
    email: "Email",
    telegram: "Telegram",
  },
};

const LOCALES = Object.keys(LABELS);

const ESCAPES = {
  "\\": "\\textbackslash{}",
  "{": "\\{",
  "}": "\\}",
  $: "\\$",
  "&": "\\&",
  "%": "\\%",
  "#": "\\#",
  _: "\\_",
  "^": "\\textasciicircum{}",
  "~": "\\textasciitilde{}",
  "\u00a0": "~",
  "\u202f": "~",
  "\u2009": "\\,",
};

const ESCAPE_PATTERN = /[\\{}$&%#_^~\u00a0\u202f\u2009]/g;

function tex(value) {
  if (value === undefined || value === null) {
    return "";
  }
  return String(value)
    .replace(/[ \t\n\r]+/g, " ")
    .trim()
    .replace(ESCAPE_PATTERN, (character) => ESCAPES[character])
    .replace(/\*\*(.+?)\*\*/g, "\\textbf{$1}");
}

function technologies(items) {
  if (!items || items.length === 0) {
    return "";
  }
  return `\\textbf{${tex(items.join(", "))}}`;
}

const PREAMBLE = String.raw`%-------------------------
% Resume in Latex
% Author : Sourabh Bajaj
% Website: https://github.com/sb2nov/resume
% License : MIT
%------------------------
%
% Generated by scripts/generate-cv.mjs -- do not edit by hand.
% Compile with XeLaTeX.

\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage{hyperref}
\usepackage{fancyhdr}

\usepackage[__BABEL__]{babel}

\usepackage{fontspec}
\setmainfont{cmunrm.otf}[
  BoldFont = cmunbx.otf,
  ItalicFont = cmunti.otf,
  BoldItalicFont = cmunbi.otf,
  SmallCapsFont = cmunrm.otf,
  SmallCapsFeatures = {Letters=SmallCaps},
  Ligatures = TeX,
]

\pagestyle{fancy}
\fancyhf{} % clear all header and footer fields
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Adjust margins
\addtolength{\oddsidemargin}{-0.375in}
\addtolength{\evensidemargin}{-0.375in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

%-------------------------
% Custom commands
\newcommand{\resumeItem}[2]{
  \item\small{
    \textbf{#1}{: #2}%
  }\par\vspace{-2pt}
}

\newcommand{\resumePlainItem}[1]{
  \item\small{#1}\par\vspace{-2pt}
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-5pt}
}

\newcommand{\resumeSubItem}[2]{\resumeItem{#1}{#2}\vspace{-4pt}}

\renewcommand{\labelitemii}{$\circ$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=*]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

\newcommand{\resumeSkillListStart}{
  \begin{itemize}[leftmargin=*, itemsep=2pt, topsep=2pt]
}
\newcommand{\resumeSkillItem}[1]{
  \item\small{#1}
}
\newcommand{\resumeSkillListEnd}{\end{itemize}}

%-------------------------------------------
%%%%%%  CV STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%
`;

function heading(cv, labels) {
  const { hero = {}, contact = {}, meta = {} } = cv;
  return [
    "%----------HEADING-----------------",
    "\\begin{tabular*}{\\textwidth}{l@{\\extracolsep{\\fill}}r}",
    `  \\textbf{\\href{${SITE_URL}}{\\Large ${tex(hero.name)}}} & ${tex(labels.email)} : \\href{mailto:${contact.email}}{${tex(contact.email)}}\\\\`,
    `  \\href{${SITE_URL}}{${tex(contact.site)}} & ${tex(labels.telegram)} : \\href{${TELEGRAM_URL}}{${tex(contact.telegram)}} \\\\`,
    "\\end{tabular*}",
    "",
    "\\vspace{5pt}",
    `{\\small ${tex(meta.description)}}`,
  ].join("\n");
}

function education(cv, labels) {
  const entries = cv.education ?? [];
  const lines = [
    "%-----------EDUCATION-----------------",
    `\\section{${tex(labels.education)}}`,
    "  \\resumeSubHeadingListStart",
  ];
  for (const entry of entries) {
    lines.push(
      "    \\resumeSubheading",
      `      {${tex(entry.institution)}}{${tex(entry.location ?? "")}}`,
      `      {${tex(entry.degree)}}{${tex(entry.period)}}`,
    );
  }
  lines.push("  \\resumeSubHeadingListEnd");
  return lines.join("\n");
}

function experience(cv, labels) {
  const entries = cv.experience ?? [];
  const lines = [
    "%-----------EXPERIENCE-----------------",
    `\\section{${tex(labels.experience)}}`,
    "  \\resumeSubHeadingListStart",
  ];
  for (const entry of entries) {
    lines.push(
      "",
      `    \\resumeSubheading{${tex(entry.company)}}{${tex(entry.location)}}{${tex(entry.role)}}{${tex(entry.period)}}`,
    );

    const highlights =
      entry.cvBullets === false ? [] : (entry.highlights ?? []);
    if (highlights.length === 0) {
      continue;
    }

    lines.push("    \\resumeItemListStart");
    for (const highlight of highlights) {
      const stack = technologies(highlight.technologies);
      const body = [tex(highlight.description), stack]
        .filter(Boolean)
        .join(" ");
      lines.push("");
      if (highlight.title) {
        lines.push(
          `    \\resumeItem{${tex(highlight.title)}}`,
          `      {${body}}`,
        );
      } else {
        lines.push(`    \\resumePlainItem{${body}}`);
      }
    }
    lines.push("", "    \\resumeItemListEnd");
  }
  lines.push("", "  \\resumeSubHeadingListEnd");
  return lines.join("\n");
}

function projects(cv, labels) {
  const entries = (cv.projects ?? []).filter(
    (entry) => entry.cvEntry !== false,
  );
  const lines = [
    "%-----------PROJECTS-----------------",
    `\\section{${tex(labels.projects)}}`,
    "  \\resumeSubHeadingListStart",
  ];
  for (const entry of entries) {
    const stack = technologies(entry.technologies);
    const name = entry.href
      ? `\\href{${entry.href}}{${tex(entry.name)}}`
      : tex(entry.name);
    const body = [tex(entry.description), stack].filter(Boolean).join(" ");
    lines.push(`    \\resumeSubItem{${name}}`, `      {${body}}`);
  }
  lines.push("  \\resumeSubHeadingListEnd");
  return lines.join("\n");
}

function achievements(cv, labels) {
  const entries = cv.achievements ?? [];
  const lines = [
    "%-----------OTHER-----------------",
    `\\section{${tex(labels.achievements)}}`,
    "  \\resumeSubHeadingListStart",
  ];
  for (const entry of entries) {
    const meta = [entry.organization, entry.period].filter(Boolean).join(", ");
    const description = tex(entry.description).replace(/\.$/, "");
    const body = meta ? `${description} (${tex(meta)}).` : `${description}.`;
    lines.push(
      "",
      `    \\resumeSubItem{${tex(entry.name)}}`,
      `      {${body}}`,
    );
  }
  lines.push("", "  \\resumeSubHeadingListEnd");
  return lines.join("\n");
}

function skills(cv, labels) {
  const entries = cv.stack ?? [];
  const lines = [
    "%-----------TECHNICAL SKILLS-----------------",
    `\\section{${tex(labels.skills)}}`,
    "  \\resumeSkillListStart",
  ];
  for (const entry of entries) {
    lines.push(`    \\resumeSkillItem{${tex((entry.items ?? []).join(", "))}}`);
  }
  lines.push("  \\resumeSkillListEnd");
  return lines.join("\n");
}

const BABEL_LANGUAGES = {
  en: "russian,english",
  ru: "english,russian",
};

function render(cv, labels, locale) {
  const sections = [
    heading(cv, labels),
    education(cv, labels),
    experience(cv, labels),
    projects(cv, labels),
    achievements(cv, labels),
    skills(cv, labels),
  ];
  const preamble = PREAMBLE.replace("__BABEL__", BABEL_LANGUAGES[locale]);
  return `${preamble}\n\\begin{document}\n\n${sections.join("\n\n\n")}\n\n\\end{document}\n`;
}

async function main() {
  await mkdir(OUTPUT_DIR, { recursive: true });

  for (const locale of LOCALES) {
    const source = join(CONTENT_DIR, `cv.${locale}.yaml`);
    const target = join(OUTPUT_DIR, `cv.${locale}.tex`);
    const cv = load(await readFile(source, "utf8"));
    await writeFile(target, render(cv, LABELS[locale], locale), "utf8");
    process.stdout.write(`${source} -> ${target}\n`);
  }
}

await main();
